In [ ]:
Consider the below code to answer further questions:

In [5]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [6]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of variable list and arraylist in pandas.

List: Lists are mutable, meaning they can be changed. They can store elements of different data types. 
Lists are implemented as dynamic arrays, which means that they can grow and shrink as needed.

ArrayList: ArrayLists are also mutable, but they can only store elements of the same data type. 
ArrayLists are implemented as fixed-size arrays, which means that they cannot grow or shrink. 
If we need to add more elements to an ArrayList, we must create a new ArrayList with a larger size.

In pandas, lists and ArrayLists are both used to store data. However, lists are more flexible because 
they can store elements of different data types and they can grow and shrink as needed. ArrayLists are 
less flexible, but they can be more efficient for storing large amounts of data of the same data type.

In [12]:
type(array_list)

numpy.ndarray

In [11]:
type(list_)

list

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [25]:
print('Data type of each and every element of the variable list:-')
for k in list_:
    print(k, type(k))

Data type of each and every element of the variable list:-
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [26]:
print('Data type of each and every element of the variable array list:-')
for i in array_list:
    print(i, type(i))

Data type of each and every element of the variable array list:-
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

In [ ]:
Yes, there is a difference in the data type of the elements present in both the variables, list_ and
array_list as now the data type of the elements in array_list is of integer and in list_, data type is string.

In [19]:
array_list = np.array(object = list_, dtype = int)

In [20]:
array_list

array([1, 2, 3, 4, 5])

In [23]:
print('Data type of each and every element of the variable list:-')
for k in list_:
    print(k, type(k))

Data type of each and every element of the variable list:-
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [24]:
print('Data type of each and every element of the variable array list:-')
for i in array_list:
    print(i, type(i))

Data type of each and every element of the variable array list:-
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [ ]:
Consider the below code to answer further questions:

In [27]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [28]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [29]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape is 2 rows and 3 columns
(ii) size is 6 as 2*3 (no. of rows multiplied with no. of columns)

In [30]:
num_array.shape

(2, 3)

In [31]:
num_array.size

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [41]:
d = np.random.randint(0,1,(3,3))

In [42]:
d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [45]:
d1 = np.identity(5)

In [46]:
d1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])